name: prerelease
on:
  push:
    branches:
      # releases/<tag>/<version>
      # releases/alpha.1/5.0.0 - will result in 5.0.0-alpha.1
      - releases/*/*
jobs:
  prerelease:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: npm
          registry-url: 'https://registry.npmjs.org'
      - name: Install core dependencies
        run: npm ci --no-audit
      - name: Install Deno
        uses: denoland/setup-deno@v1
        with:
          # Should match the `DENO_VERSION_RANGE` from https://github.com/netlify/build/blob/main/packages/edge-bundler/node/bridge.ts#L20
          deno-version: v1.46.3
      - name: Extract tag and version
        id: extract
        run: |-
          ref=${{ github.ref }}
          branch=${ref:11}
          tag_version=${branch:9}
          tag=${tag_version%/*}
          version=${tag_version##*/}
          echo "tag=${tag}" >> $GITHUB_OUTPUT
          echo "version=${version}" >> $GITHUB_OUTPUT
      - name: Log versions
        run: |-
          echo tag=${{ steps.extract.outputs.tag }}
          echo version=${{ steps.extract.outputs.version }}
      - name: Setup git user
        run: git config --global user.name github-actions
      - name: Setup git email
        run: git config --global user.email github-actions@github.com
      - name: Run npm version
        run:
          npm version ${{ steps.extract.outputs.version }}-${{ steps.extract.outputs.tag }}
          --allow-same-version
      - name: Push changes
        run: git push --follow-tags
      - name: build
        run: npm run build
      - name: Run npm publish
        run: npm publish --tag=${{ steps.extract.outputs.tag }}
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
